var Globals =
    {
        "SCREEN_WIDTH" : 0,
        "SCREEN_HEIGHT" : 0,
        "app" : null,
        "loader" : null,
        "audioPlayer" : null,
        "TOTAL_TYPES_OF_CARD_AVAILABLE" : 81,
        "CARD_RES_PREFIX" : "elem_",
        "CARD_BACK_FILENAME" : "card_back",
        "CARD_FRONT_FILENAME" : "card_front",
        "ASSETS_ROOT_FOLDER" : "./assets/",
        "IMAGES_FOLDER" : "images/",
        "IMAGES_EXTENSION" : ".png",
        "AUDIO_FOLDER" : "audio/",
        "AUDIO_EXTENSION" : ".mp3",
        "CARD_FLIP_SOUND_FILENAME" : "flip",
        "SWISH_SOUND_FILENAME" : "swish",
        "BG_MUSIC_FILENAME" : "maple",
        "TABLE_SPRITE_FILENAME" : "table",
        "GUI" : null,
        "W" : 2,
        "H" : 2,
        "NUM_PLAYERS" : 1,
        "Player 1" : "Player 1",
        "Player 2" : "Player 2",
        "Player 3" : "Player 3",
        "Player 4" : "Player 4"
    };